name: Publish Package for Specific Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g., 'v3.11.3')"
        required: true

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract Semantic Version Number
        id: extract_version
        shell: pwsh
        run: |
          $version = "${{ inputs.version }}" -replace '^v', ''
          echo "version_number=$version" >> $env:GITHUB_OUTPUT

      - name: Build the packages
        run:  .\pack.ps1 -Version "${{ github.event.inputs.version }}"

      - name: Save a copy of working directory for debugging
        uses: actions/upload-artifact@v4
        with:
          name: working-directory
          path: ${{ github.event.inputs.version }}
          retention-days: 1

      - name: Enable MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.1

      - name: Test the packages
        run:  .\test.ps1 -Version "${{ github.event.inputs.version }}"

      - name: Push nlohmann.json Package
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          nuget push "${{ inputs.version }}/nlohmann.json.${{ steps.extract_version.outputs.version_number }}.nupkg" `
            -ApiKey $env:NUGET_API_KEY `
            -SkipDuplicate `
            -Source https://api.nuget.org/v3/index.json

      - name: Push nlohmann.json.decomposed Package
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          nuget push "${{ inputs.version }}/nlohmann.json.decomposed.${{ steps.extract_version.outputs.version_number }}.nupkg" `
            -ApiKey $env:NUGET_API_KEY `
            -SkipDuplicate `
            -Source https://api.nuget.org/v3/index.json
